---
- hosts: all
  vars:
    current_path: "{{ lookup('env','PWD') }}"
    local_home: "{{ lookup('env','HOME') }}"

    project_home: "{{ lookup('env','DESKTOP_PROJECT_DIR') | default(current_path,true) }}"
    settings_home: "{{ lookup('env','DESKTOP_SETTINGS_DIR') }}"

    linux_gnome_settings_yaml: "{{ settings_home }}/linux-gnome-settings.yml"     
    linux_packages_yaml: "{{ settings_home }}/linux-packages.yml"

    macos_configure_os_settings_yaml: "{{ settings_home }}/macos-configure-os-settings.yml"     
    macos_brew_yaml: "{{ settings_home }}/macos-brew.yml"

    docker_applications_yaml:  "{{ settings_home }}/docker-applications.yml"
    custom_roles_yaml: "{{ settings_home }}/customroles.yml"

    desktop_directory: "{{ local_home }}/.desktop/"

  tasks:
    # LINUX
    - include_role: 
        name: linux-packages
      when: ansible_system == 'Linux'
      vars:
        packages: "{{ linux_packages_yaml }}"

    # LINUX
    - include_role: 
        name: linux-install-docker
      when: ansible_system == 'Linux'
      vars:
        non_root_user: "{{ ansible_user_id }}" 

    # LINUX
    - include_role:
        name: linux-gnome-desktop-settings
      when: ansible_system == 'Linux'
      vars:
        gnomeSettings: "{{ linux_gnome_settings_yaml }}"
        desktop_dir: "{{ desktop_directory }}"

    # MAC (Darwin)
    - include_role:
        name: macos-homebrew
      when: ansible_system == 'Darwin'
      vars:
        macos_homebrew: "{{ macos_brew_yaml }}"
        desktop_dir: "{{ desktop_directory }}"

    # MAC (Darwin)
    - include_role:
        name: macos-configure-os-settings
      when: ansible_system == 'Darwin'
      vars:
        macos_settings: "{{ macos_configure_os_settings_yaml }}"
        desktop_dir: "{{ desktop_directory }}"

    # # LINUX AND MAC (Darwin) - docker required
    # - include_role:
    #     name: docker-applications
    #   when: (ansible_system == 'Linux') or (ansible_system == 'Darwin')
    #   vars:
    #     application_setup: "{{ docker_applications_yaml }}"
    #     desktop_dir: "{{ desktop_directory }}"

    # CUSTOM ROLE
    - include_role: 
        name: custom-roles
      vars:
        custom_roles_dir: "{{ settings_home }}/custom_roles/"
